// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WePlayRises.Crowdsourcing.Infra.Context;

#nullable disable

namespace WePlayRises.Crowdsourcing.Infra.Migrations
{
    [DbContext(typeof(CrowdsourcingContext))]
    [Migration("20260216165542_AddMotivoCierreToNecesidad")]
    partial class AddMotivoCierreToNecesidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoAcuerdoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoAcuerdo_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaFinPrevista")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ImporteAnticipo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteTotalPactado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<Guid>("NecesidadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Necesidad_Id");

                    b.Property<Guid?>("PerfilProfesionalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilProfesional_Id");

                    b.Property<decimal?>("PorcentajeAnticipo")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid?>("PropuestaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Propuesta_Id");

                    b.Property<string>("TituloInterno")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserIdProveedor")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NecesidadId")
                        .HasDatabaseName("IX_AcuerdoCrowdsourcing_Necesidad");

                    b.HasIndex("PropuestaId");

                    b.HasIndex("ArtistaId", "EstadoAcuerdoId")
                        .HasDatabaseName("IX_AcuerdoCrowdsourcing_Artista_Estado");

                    b.ToTable("AcuerdoCrowdsourcing", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcingEntregable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcuerdoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Acuerdo_Id");

                    b.Property<string>("ComentarioAprobacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoEntregableId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoEntregable_Id");

                    b.Property<DateTime?>("FechaAprobacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("MilestoneId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Milestone_Id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlRecurso")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoId");

                    b.HasIndex("MilestoneId");

                    b.ToTable("AcuerdoCrowdsourcing_Entregable", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcingMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcuerdoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Acuerdo_Id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaLimite")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteParcial")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<decimal?>("PorcentajeParcial")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoId");

                    b.ToTable("AcuerdoCrowdsourcing_Milestone", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.ConversacionCrowdsourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcuerdoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Acuerdo_Id");

                    b.Property<string>("Asunto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaUltimoMensaje")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid?>("NecesidadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Necesidad_Id");

                    b.Property<string>("UserIdArtista")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserIdProveedor")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoId");

                    b.HasIndex("NecesidadId");

                    b.ToTable("ConversacionCrowdsourcing", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MaestraCategoriaRol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Orden");

                    b.ToTable("MaestrasCategoriaRol", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icono = "music",
                            Nombre = "Produccion Musical",
                            Orden = 1
                        },
                        new
                        {
                            Id = 2,
                            Icono = "sliders",
                            Nombre = "Ingenieria de Audio",
                            Orden = 2
                        },
                        new
                        {
                            Id = 3,
                            Icono = "palette",
                            Nombre = "Diseno y Creatividad",
                            Orden = 3
                        },
                        new
                        {
                            Id = 4,
                            Icono = "megaphone",
                            Nombre = "Marketing y Promocion",
                            Orden = 4
                        },
                        new
                        {
                            Id = 5,
                            Icono = "briefcase",
                            Nombre = "Gestion y Legal",
                            Orden = 5
                        },
                        new
                        {
                            Id = 6,
                            Icono = "mic",
                            Nombre = "Produccion de Eventos / Live",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MaestraRolProfesional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoriaRolId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModalidadCobro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("CategoriaRolId");

                    b.ToTable("MaestrasRolProfesional", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaRolId = 1,
                            Descripcion = "Dirige la vision sonora del proyecto completo",
                            ModalidadCobro = "Por proyecto o por cancion",
                            Nombre = "Productor musical"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaRolId = 1,
                            Descripcion = "Crea arreglos instrumentales y vocales",
                            ModalidadCobro = "Por cancion",
                            Nombre = "Arreglista / Compositor"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaRolId = 1,
                            Descripcion = "Crea bases ritmicas y beats",
                            ModalidadCobro = "Por beat",
                            Nombre = "Beatmaker"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaRolId = 1,
                            Descripcion = "Coordina ensayos y direccion artistica en vivo",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Director musical"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaRolId = 1,
                            Descripcion = "Interpreta instrumentos para grabaciones",
                            ModalidadCobro = "Por sesion",
                            Nombre = "Musico de sesion"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaRolId = 1,
                            Descripcion = "Prepara y entrena vocalmente al artista",
                            ModalidadCobro = "Por sesion",
                            Nombre = "Vocal coach"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaRolId = 2,
                            Descripcion = "Captura audio de alta calidad en estudio",
                            ModalidadCobro = "Por dia",
                            Nombre = "Ingeniero de grabacion"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaRolId = 2,
                            Descripcion = "Equilibra y procesa todas las pistas grabadas",
                            ModalidadCobro = "Por cancion",
                            Nombre = "Ingeniero de mezcla"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaRolId = 2,
                            Descripcion = "Optimiza el audio final para distribucion",
                            ModalidadCobro = "Por cancion",
                            Nombre = "Ingeniero de mastering"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaRolId = 2,
                            Descripcion = "Gestiona el sonido en eventos en vivo",
                            ModalidadCobro = "Por evento",
                            Nombre = "Tecnico de sonido (live)"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaRolId = 2,
                            Descripcion = "Crea efectos de sonido y ambientes",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Disenador sonoro"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Crea portadas, logos y material visual",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Disenador grafico"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Sesiones fotograficas profesionales",
                            ModalidadCobro = "Por sesion",
                            Nombre = "Fotografo"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Dirige la produccion audiovisual del videoclip",
                            ModalidadCobro = "Por video",
                            Nombre = "Director de videoclip"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Edita y post-produce material audiovisual",
                            ModalidadCobro = "Por video",
                            Nombre = "Editor de video"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Crea animaciones y graficos en movimiento",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Animador / Motion graphics"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Define la estetica visual del proyecto",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Director de arte"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            CategoriaRolId = 3,
                            Descripcion = "Disena la imagen y vestuario del artista",
                            ModalidadCobro = "Por sesion",
                            Nombre = "Estilista / Vestuarista"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            CategoriaRolId = 4,
                            Descripcion = "Gestiona redes sociales y comunidad online",
                            ModalidadCobro = "Por mes",
                            Nombre = "Community manager"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            CategoriaRolId = 4,
                            Descripcion = "Gestiona prensa y relaciones publicas",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Publicista musical"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            CategoriaRolId = 4,
                            Descripcion = "Campanas de publicidad digital (Spotify, Meta, etc.)",
                            ModalidadCobro = "Por mes",
                            Nombre = "Especialista en ads"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            CategoriaRolId = 4,
                            Descripcion = "Produce contenido para redes sociales y plataformas",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Creador de contenido"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            CategoriaRolId = 4,
                            Descripcion = "Gestiona la distribucion en plataformas de streaming",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Experto en distribucion digital"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            CategoriaRolId = 5,
                            Descripcion = "Gestiona la carrera y negocios del artista",
                            ModalidadCobro = "Por mes",
                            Nombre = "Manager artistico"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            CategoriaRolId = 5,
                            Descripcion = "Asesoria legal en contratos y derechos",
                            ModalidadCobro = "Por hora",
                            Nombre = "Abogado musical"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            CategoriaRolId = 5,
                            Descripcion = "Registro y gestion de derechos de propiedad intelectual",
                            ModalidadCobro = "Por proyecto",
                            Nombre = "Especialista en derechos de autor"
                        },
                        new
                        {
                            Id = 27,
                            Activo = true,
                            CategoriaRolId = 6,
                            Descripcion = "Organiza y promueve conciertos y eventos",
                            ModalidadCobro = "Por evento",
                            Nombre = "Promotor de eventos"
                        },
                        new
                        {
                            Id = 28,
                            Activo = true,
                            CategoriaRolId = 6,
                            Descripcion = "Coordina la logistica del escenario",
                            ModalidadCobro = "Por evento",
                            Nombre = "Stage manager"
                        },
                        new
                        {
                            Id = 29,
                            Activo = true,
                            CategoriaRolId = 6,
                            Descripcion = "Disena y opera la iluminacion de eventos",
                            ModalidadCobro = "Por evento",
                            Nombre = "Tecnico de iluminacion"
                        },
                        new
                        {
                            Id = 30,
                            Activo = true,
                            CategoriaRolId = 6,
                            Descripcion = "Gestiona la logistica de giras",
                            ModalidadCobro = "Por dia",
                            Nombre = "Roadie / Tour manager"
                        });
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MensajeCrowdsourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Conversacion_Id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaLeido")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("UrlAdjunto")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserIdRemitente")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.ToTable("MensajeCrowdsourcing", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.NecesidadCrowdsourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoNecesidadId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoNecesidad_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaInicioPrevista")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaLimitePropuestas")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("ModalidadTrabajoId")
                        .HasColumnType("int")
                        .HasColumnName("ModalidadTrabajo_Id");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<string>("MotivoCierre")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("PresupuestoMax")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PresupuestoMin")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("ProyectoArtisticoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProyectoArtistico_Id");

                    b.Property<int>("TipoNecesidadId")
                        .HasColumnType("int")
                        .HasColumnName("TipoNecesidad_Id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UbicacionCiudad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UbicacionPais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId", "EstadoNecesidadId")
                        .HasDatabaseName("IX_NecesidadCrowdsourcing_Artista_Estado");

                    b.ToTable("NecesidadCrowdsourcing", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PlantillaProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Activo");

                    b.HasIndex("Orden");

                    b.ToTable("PlantillasProyecto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Descripcion = "Todas las fases para grabar tu primer disco: desde pre-produccion hasta el master final",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "music",
                            Nombre = "Grabar un Album / EP",
                            Orden = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            Descripcion = "Todo lo necesario para producir un videoclip profesional",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "video",
                            Nombre = "Produccion de Videoclip",
                            Orden = 2
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            Descripcion = "Planifica y ejecuta una gira de conciertos",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "map",
                            Nombre = "Organizar Gira / Tour",
                            Orden = 3
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            Descripcion = "Estrategia completa de promocion y marketing musical",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "megaphone",
                            Nombre = "Campana de Marketing",
                            Orden = 4
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            Descripcion = "Todo lo necesario para lanzar un single con impacto",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "disc",
                            Nombre = "Lanzamiento de Single",
                            Orden = 5
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Activo = true,
                            Descripcion = "Construye tu identidad digital y presencia en redes",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Icono = "globe",
                            Nombre = "Presencia Online",
                            Orden = 6
                        });
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PlantillaProyectoNecesidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Fase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("MonedaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("PlantillaProyectoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("PrecioMaxOrientativo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("PrecioMinOrientativo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Media");

                    b.Property<int>("RolProfesionalId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaProyectoId");

                    b.HasIndex("Prioridad");

                    b.HasIndex("RolProfesionalId");

                    b.ToTable("PlantillasProyectoNecesidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111101"),
                            Descripcion = "Crear arreglos instrumentales y vocales",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 1,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 2,
                            Titulo = "Composicion y arreglos musicales"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111102"),
                            Descripcion = "Definir la vision sonora del proyecto",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 2,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 3000m,
                            PrecioMinOrientativo = 500m,
                            Prioridad = "Alta",
                            RolProfesionalId = 1,
                            Titulo = "Produccion musical"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111103"),
                            Descripcion = "Preparacion vocal para grabacion",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 3,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 500m,
                            PrecioMinOrientativo = 100m,
                            Prioridad = "Media",
                            RolProfesionalId = 6,
                            Titulo = "Coaching vocal"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111104"),
                            Descripcion = "Captura de audio en estudio",
                            Fase = "Grabacion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 4,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 7,
                            Titulo = "Ingeniero de grabacion"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111105"),
                            Descripcion = "Instrumentistas para grabacion",
                            Fase = "Grabacion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 5,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 5,
                            Titulo = "Musicos de sesion"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111106"),
                            Descripcion = "Equilibrar y procesar todas las pistas",
                            Fase = "Mezcla y Master",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 6,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 8,
                            Titulo = "Mezcla de pistas"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111107"),
                            Descripcion = "Optimizar audio final para distribucion",
                            Fase = "Mezcla y Master",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 7,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 9,
                            Titulo = "Mastering"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111108"),
                            Descripcion = "Crear portada del album",
                            Fase = "Diseno y Produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 8,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 12,
                            Titulo = "Diseno de portada"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111109"),
                            Descripcion = "Fotos promocionales del artista",
                            Fase = "Diseno y Produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 9,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 13,
                            Titulo = "Sesion fotografica"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            Descripcion = "Subir a plataformas de streaming",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 10,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 300m,
                            PrecioMinOrientativo = 50m,
                            Prioridad = "Alta",
                            RolProfesionalId = 23,
                            Titulo = "Distribucion digital"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Descripcion = "Campana de prensa y publicity",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 11,
                            PlantillaProyectoId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 20,
                            Titulo = "Publicidad y prensa"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222201"),
                            Descripcion = "Concepto creativo y storyboard",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 1,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 3000m,
                            PrecioMinOrientativo = 500m,
                            Prioridad = "Alta",
                            RolProfesionalId = 14,
                            Titulo = "Direccion de videoclip"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222202"),
                            Descripcion = "Definir estetica visual del video",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 2,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 17,
                            Titulo = "Director de arte"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222203"),
                            Descripcion = "Imagen y vestuario del artista",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 3,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 18,
                            Titulo = "Estilista / Vestuarista"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222204"),
                            Descripcion = "Camaras, iluminacion y equipo tecnico",
                            Fase = "Grabacion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 4,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 5000m,
                            PrecioMinOrientativo = 800m,
                            Prioridad = "Alta",
                            RolProfesionalId = 14,
                            Titulo = "Equipo de grabacion video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222205"),
                            Descripcion = "Diseno y operacion de iluminacion",
                            Fase = "Grabacion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 5,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 29,
                            Titulo = "Iluminacion"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222206"),
                            Descripcion = "Montaje y edicion del videoclip",
                            Fase = "Post-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 6,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 15,
                            Titulo = "Edicion de video"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222207"),
                            Descripcion = "Efectos visuales y graficos animados",
                            Fase = "Post-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 7,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Media",
                            RolProfesionalId = 16,
                            Titulo = "Animacion / Motion graphics"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222208"),
                            Descripcion = "Color grading profesional",
                            Fase = "Post-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 8,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 15,
                            Titulo = "Correccion de color"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222209"),
                            Descripcion = "Teasers y clips promocionales",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 9,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 500m,
                            PrecioMinOrientativo = 100m,
                            Prioridad = "Media",
                            RolProfesionalId = 22,
                            Titulo = "Contenido para redes"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222210"),
                            Descripcion = "Estrategia de lanzamiento del video",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 10,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 21,
                            Titulo = "Campana de lanzamiento"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222211"),
                            Descripcion = "YouTube, Vevo y redes sociales",
                            Fase = "Distribucion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 11,
                            PlantillaProyectoId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PrecioMaxOrientativo = 200m,
                            PrecioMinOrientativo = 50m,
                            Prioridad = "Baja",
                            RolProfesionalId = 23,
                            Titulo = "Distribucion en plataformas"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            Descripcion = "Planificacion y logistica de la gira",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 1,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 3000m,
                            PrecioMinOrientativo = 500m,
                            Prioridad = "Alta",
                            RolProfesionalId = 30,
                            Titulo = "Tour manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            Descripcion = "Conseguir venues y negociar fechas",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 2,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 27,
                            Titulo = "Promotor de eventos"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            Descripcion = "Preparacion del show en vivo",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 3,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 4,
                            Titulo = "Director musical"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            Descripcion = "Revision de contratos con venues",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 4,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 25,
                            Titulo = "Abogado musical"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            Descripcion = "Sonido en vivo para cada show",
                            Fase = "Produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 5,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 10,
                            Titulo = "Tecnico de sonido"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333306"),
                            Descripcion = "Iluminacion para cada show",
                            Fase = "Produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 6,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 29,
                            Titulo = "Tecnico de iluminacion"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333307"),
                            Descripcion = "Coordinacion de escenario",
                            Fase = "Produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 7,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 28,
                            Titulo = "Stage manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333308"),
                            Descripcion = "Banda para el show en vivo",
                            Fase = "Produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 8,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 3000m,
                            PrecioMinOrientativo = 500m,
                            Prioridad = "Alta",
                            RolProfesionalId = 5,
                            Titulo = "Musicos de sesion"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333309"),
                            Descripcion = "Promocion en redes de cada fecha",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 9,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 19,
                            Titulo = "Community manager"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333310"),
                            Descripcion = "Documentar la gira visualmente",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 10,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Baja",
                            RolProfesionalId = 13,
                            Titulo = "Fotografo de gira"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333311"),
                            Descripcion = "Contenido backstage y making of",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 11,
                            PlantillaProyectoId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Baja",
                            RolProfesionalId = 22,
                            Titulo = "Creador de contenido"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444401"),
                            Descripcion = "Plan de comunicacion y prensa",
                            Fase = "Estrategia",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 1,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 20,
                            Titulo = "Publicista musical"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444402"),
                            Descripcion = "Campanas de publicidad digital",
                            Fase = "Estrategia",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 2,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 21,
                            Titulo = "Especialista en ads"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444403"),
                            Descripcion = "Gestion de redes sociales",
                            Fase = "Contenido",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 3,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 19,
                            Titulo = "Community manager"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444404"),
                            Descripcion = "Contenido visual y audiovisual",
                            Fase = "Contenido",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 4,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 22,
                            Titulo = "Creador de contenido"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444405"),
                            Descripcion = "Sesion de fotos promocionales",
                            Fase = "Contenido",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 5,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 13,
                            Titulo = "Fotografo"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444406"),
                            Descripcion = "Material grafico para campana",
                            Fase = "Contenido",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 6,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 12,
                            Titulo = "Disenador grafico"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444407"),
                            Descripcion = "Plataformas de streaming y tiendas",
                            Fase = "Distribucion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 7,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 300m,
                            PrecioMinOrientativo = 50m,
                            Prioridad = "Alta",
                            RolProfesionalId = 23,
                            Titulo = "Distribucion digital"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444408"),
                            Descripcion = "Registro de obra en entidades",
                            Fase = "Legal",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 8,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 500m,
                            PrecioMinOrientativo = 100m,
                            Prioridad = "Media",
                            RolProfesionalId = 26,
                            Titulo = "Registro de derechos"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444409"),
                            Descripcion = "Coordinacion general de la campana",
                            Fase = "Seguimiento",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 9,
                            PlantillaProyectoId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PrecioMaxOrientativo = 1500m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Media",
                            RolProfesionalId = 24,
                            Titulo = "Manager artistico"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555501"),
                            Descripcion = "Produccion del single",
                            Fase = "Pre-produccion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 1,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 2000m,
                            PrecioMinOrientativo = 300m,
                            Prioridad = "Alta",
                            RolProfesionalId = 1,
                            Titulo = "Produccion musical"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555502"),
                            Descripcion = "Grabacion del single",
                            Fase = "Grabacion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 2,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 7,
                            Titulo = "Ingeniero de grabacion"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555503"),
                            Descripcion = "Mezcla del single",
                            Fase = "Mezcla y Master",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 3,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 8,
                            Titulo = "Mezcla"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555504"),
                            Descripcion = "Mastering del single",
                            Fase = "Mezcla y Master",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 4,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 500m,
                            PrecioMinOrientativo = 100m,
                            Prioridad = "Alta",
                            RolProfesionalId = 9,
                            Titulo = "Mastering"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555505"),
                            Descripcion = "Portada del single",
                            Fase = "Diseno",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 5,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 500m,
                            PrecioMinOrientativo = 100m,
                            Prioridad = "Media",
                            RolProfesionalId = 12,
                            Titulo = "Diseno de portada"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555506"),
                            Descripcion = "Subida a plataformas",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 6,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 200m,
                            PrecioMinOrientativo = 50m,
                            Prioridad = "Alta",
                            RolProfesionalId = 23,
                            Titulo = "Distribucion digital"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555507"),
                            Descripcion = "Publicidad digital del single",
                            Fase = "Promocion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 7,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Media",
                            RolProfesionalId = 21,
                            Titulo = "Campana de ads"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555508"),
                            Descripcion = "Registro del single",
                            Fase = "Legal",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 8,
                            PlantillaProyectoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PrecioMaxOrientativo = 300m,
                            PrecioMinOrientativo = 50m,
                            Prioridad = "Media",
                            RolProfesionalId = 26,
                            Titulo = "Registro de derechos"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666601"),
                            Descripcion = "Logo, paleta de colores, branding",
                            Fase = "Identidad",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 1,
                            PlantillaProyectoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PrecioMaxOrientativo = 1000m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 12,
                            Titulo = "Disenador grafico"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666602"),
                            Descripcion = "Sesion de fotos para perfiles",
                            Fase = "Contenido",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 2,
                            PlantillaProyectoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Alta",
                            RolProfesionalId = 13,
                            Titulo = "Fotografo"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666603"),
                            Descripcion = "Configuracion y gestion de redes",
                            Fase = "Redes",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 3,
                            PlantillaProyectoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PrecioMaxOrientativo = 800m,
                            PrecioMinOrientativo = 200m,
                            Prioridad = "Alta",
                            RolProfesionalId = 19,
                            Titulo = "Community manager"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666604"),
                            Descripcion = "Contenido inicial para perfiles",
                            Fase = "Contenido",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 4,
                            PlantillaProyectoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PrecioMaxOrientativo = 600m,
                            PrecioMinOrientativo = 150m,
                            Prioridad = "Media",
                            RolProfesionalId = 22,
                            Titulo = "Creador de contenido"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666605"),
                            Descripcion = "Perfiles en plataformas de streaming",
                            Fase = "Distribucion",
                            FechaCreacion = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MonedaId = 1,
                            Orden = 5,
                            PlantillaProyectoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PrecioMaxOrientativo = 200m,
                            PrecioMinOrientativo = 50m,
                            Prioridad = "Media",
                            RolProfesionalId = 23,
                            Titulo = "Distribucion digital"
                        });
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PropuestaCrowdsourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DiasEstimados")
                        .HasColumnType("int");

                    b.Property<int>("EstadoPropuestaId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoPropuesta_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("MensajePropuesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<Guid>("NecesidadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Necesidad_Id");

                    b.Property<Guid?>("PerfilProfesionalId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PerfilProfesional_Id");

                    b.Property<decimal>("PrecioPropuesto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("NecesidadId");

                    b.ToTable("PropuestaCrowdsourcing", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.ValoracionCrowdsourcing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AcuerdoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Acuerdo_Id");

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Puntuacion")
                        .HasColumnType("tinyint");

                    b.Property<int>("TipoValoracionId")
                        .HasColumnType("int")
                        .HasColumnName("TipoValoracion_Id");

                    b.Property<string>("UserIdAutor")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserIdValorado")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AcuerdoId");

                    b.ToTable("ValoracionCrowdsourcing", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.NecesidadCrowdsourcing", "Necesidad")
                        .WithMany("Acuerdos")
                        .HasForeignKey("NecesidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.PropuestaCrowdsourcing", "Propuesta")
                        .WithMany("Acuerdos")
                        .HasForeignKey("PropuestaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Necesidad");

                    b.Navigation("Propuesta");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcingEntregable", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", "Acuerdo")
                        .WithMany("Entregables")
                        .HasForeignKey("AcuerdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcingMilestone", "Milestone")
                        .WithMany()
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Acuerdo");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcingMilestone", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", "Acuerdo")
                        .WithMany("Milestones")
                        .HasForeignKey("AcuerdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acuerdo");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.ConversacionCrowdsourcing", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", "Acuerdo")
                        .WithMany("Conversaciones")
                        .HasForeignKey("AcuerdoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.NecesidadCrowdsourcing", "Necesidad")
                        .WithMany("Conversaciones")
                        .HasForeignKey("NecesidadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Acuerdo");

                    b.Navigation("Necesidad");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MaestraRolProfesional", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.MaestraCategoriaRol", "CategoriaRol")
                        .WithMany("Roles")
                        .HasForeignKey("CategoriaRolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaRol");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MensajeCrowdsourcing", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.ConversacionCrowdsourcing", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversacion");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PlantillaProyectoNecesidad", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.PlantillaProyecto", "PlantillaProyecto")
                        .WithMany("Necesidades")
                        .HasForeignKey("PlantillaProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.MaestraRolProfesional", "RolProfesional")
                        .WithMany("PlantillasNecesidades")
                        .HasForeignKey("RolProfesionalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantillaProyecto");

                    b.Navigation("RolProfesional");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PropuestaCrowdsourcing", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.NecesidadCrowdsourcing", "Necesidad")
                        .WithMany("Propuestas")
                        .HasForeignKey("NecesidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Necesidad");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.ValoracionCrowdsourcing", b =>
                {
                    b.HasOne("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", "Acuerdo")
                        .WithMany("Valoraciones")
                        .HasForeignKey("AcuerdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acuerdo");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.AcuerdoCrowdsourcing", b =>
                {
                    b.Navigation("Conversaciones");

                    b.Navigation("Entregables");

                    b.Navigation("Milestones");

                    b.Navigation("Valoraciones");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.ConversacionCrowdsourcing", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MaestraCategoriaRol", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.MaestraRolProfesional", b =>
                {
                    b.Navigation("PlantillasNecesidades");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.NecesidadCrowdsourcing", b =>
                {
                    b.Navigation("Acuerdos");

                    b.Navigation("Conversaciones");

                    b.Navigation("Propuestas");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PlantillaProyecto", b =>
                {
                    b.Navigation("Necesidades");
                });

            modelBuilder.Entity("WePlayRises.Crowdsourcing.Domain.Model.PropuestaCrowdsourcing", b =>
                {
                    b.Navigation("Acuerdos");
                });
#pragma warning restore 612, 618
        }
    }
}
