<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WePlayRises.BuildingBlocks.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>WePlayRises.BuildingBlocks.$(MSBuildProjectName)</RootNamespace>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Description>WePlayRises.BuildingBlocks.Caching contains cache logic and providers.</Description>
    <Copyright>Copyright © 2026</Copyright>
    <Authors>WePlayRises</Authors>
    <Company>WePlayRises</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kernel\Kernel.csproj" />
  </ItemGroup>

</Project>
