// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WePlayRises.Crowdpromotion.Infra.Context;

#nullable disable

namespace WePlayRises.Crowdpromotion.Infra.Migrations
{
    [DbContext(typeof(CrowdpromotionContext))]
    [Migration("20260324181647_InitialCrowdpromotion")]
    partial class InitialCrowdpromotion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AportacionCrowdfundingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AportacionCrowdfunding_Id");

                    b.Property<Guid?>("CampaniaCrowdfundingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CampaniaCrowdfunding_Id");

                    b.Property<string>("CodigoReferido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ImporteAsociado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("IpOrigen")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<Guid?>("PedidoCrowdfundingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PedidoCrowdfunding_Id");

                    b.Property<Guid?>("ProgramaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Programa_Id");

                    b.Property<Guid?>("PromoProgramaPromotorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PromoPrograma_Promotor_Id");

                    b.Property<Guid?>("PromotorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Promotor_Id");

                    b.Property<int>("TipoEventoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoEvento_Id");

                    b.Property<string>("UrlOrigen")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("UrlReferer")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("UserAgentOrigen")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserIdAfectado")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UtmCampaign")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtmMedium")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UtmSource")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferido")
                        .HasDatabaseName("IX_PromoEvento_CodigoReferido");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_PromoEvento_FechaCreacion");

                    b.HasIndex("PromoProgramaPromotorId")
                        .HasDatabaseName("IX_PromoEvento_ProgramaPromotor");

                    b.HasIndex("ProgramaId", "FechaCreacion")
                        .HasDatabaseName("IX_PromoEvento_Programa_Fecha");

                    b.HasIndex("PromotorId", "TipoEventoId", "FechaCreacion")
                        .HasDatabaseName("IX_PromoEvento_Promotor_Tipo_Fecha");

                    b.ToTable("PromoEvento", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoPrograma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<Guid?>("CampaniaCrowdfundingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CampaniaCrowdfunding_Id");

                    b.Property<string>("CodigoTrackingBase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("ComisionPorClick")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<decimal?>("ComisionPorConversion")
                        .HasColumnType("decimal(18, 4)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaFin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ImporteComisionFija")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("ImporteComisionPorcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<decimal?>("PresupuestoTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("ProyectoArtisticoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProyectoArtistico_Id");

                    b.Property<int>("TipoPromoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoPromo_Id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UrlLanding")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId", "CodigoTrackingBase")
                        .IsUnique()
                        .HasDatabaseName("IX_PromoPrograma_Artista_CodigoTracking")
                        .HasFilter("[CodigoTrackingBase] IS NOT NULL");

                    b.HasIndex("ArtistaId", "EsActivo")
                        .HasDatabaseName("IX_PromoPrograma_Artista_Activo");

                    b.ToTable("PromoPrograma", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoProgramaPromotor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoReferido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsAprobado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsBloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("FechaBaja")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Programa_Id");

                    b.Property<Guid>("PromotorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Promotor_Id");

                    b.Property<int>("TotalClicks")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalComisionesGeneradas")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("TotalConversiones")
                        .HasColumnType("int");

                    b.Property<string>("UrlReferido")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoReferido")
                        .HasDatabaseName("IX_PromoProgramaPromotor_CodigoReferido");

                    b.HasIndex("PromotorId");

                    b.HasIndex("ProgramaId", "PromotorId")
                        .IsUnique()
                        .HasDatabaseName("IX_PromoProgramaPromotor_Programa_Promotor");

                    b.ToTable("PromoProgramaPromotor", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsRepetible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaFin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal?>("ImporteRecompensa")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("InstruccionesUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MaxRepeticiones")
                        .HasColumnType("int");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("ProgramaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Programa_Id");

                    b.Property<int?>("PuntosRecompensa")
                        .HasColumnType("int");

                    b.Property<int>("TipoEventoPromoId")
                        .HasColumnType("int")
                        .HasColumnName("TipoEventoPromo_Id");

                    b.Property<int?>("TipoRewardId")
                        .HasColumnType("int")
                        .HasColumnName("TipoReward_Id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaId");

                    b.ToTable("PromoTarea", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoTareaPromotor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComentarioPromotor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComentarioValidacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoTareaId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoTarea_Id");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaValidado")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("ProgramaPromotorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProgramaPromotor_Id");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Tarea_Id");

                    b.Property<string>("UrlPruebaCompletado")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramaPromotorId");

                    b.HasIndex("TareaId");

                    b.ToTable("PromoTareaPromotor", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.Promotor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmailContacto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("FanProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FanProfile_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NombrePublico")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("SeguidoresTotales")
                        .HasColumnType("int");

                    b.Property<int>("TipoPromotorId")
                        .HasColumnType("int")
                        .HasColumnName("TipoPromotor_Id");

                    b.Property<string>("UrlInstagram")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UrlSitioWeb")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UrlTikTok")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UrlTwitter")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UrlYouTube")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Promotor_UserId");

                    b.ToTable("Promotor", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromotorWallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<Guid>("PromotorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Promotor_Id");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalGanado")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalRetirado")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex("PromotorId", "MonedaId")
                        .IsUnique()
                        .HasDatabaseName("IX_PromotorWallet_Promotor_Moneda");

                    b.ToTable("PromotorWallet", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromotorWalletTransaccion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CampaniaPayoutId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CampaniaPayout_Id");

                    b.Property<string>("Concepto")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("EstadoTransaccionId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoTransaccion_Id");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid?>("PromoEventoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PromoEvento_Id");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TipoRewardId")
                        .HasColumnType("int")
                        .HasColumnName("TipoReward_Id");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Wallet_Id");

                    b.HasKey("Id");

                    b.HasIndex("FechaCreacion")
                        .HasDatabaseName("IX_PromotorWalletTransaccion_FechaCreacion");

                    b.HasIndex("PromoEventoId");

                    b.HasIndex("WalletId", "FechaCreacion")
                        .HasDatabaseName("IX_PromotorWalletTransaccion_Wallet_Fecha");

                    b.HasIndex("WalletId", "EsCredito", "EstadoTransaccionId")
                        .HasDatabaseName("IX_PromotorWalletTransaccion_Wallet_EsCredito_Estado");

                    b.ToTable("PromotorWalletTransaccion", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoEvento", b =>
                {
                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromoPrograma", "Programa")
                        .WithMany("Eventos")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.Promotor", "Promotor")
                        .WithMany()
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Programa");

                    b.Navigation("Promotor");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoProgramaPromotor", b =>
                {
                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromoPrograma", "Programa")
                        .WithMany("Promotores")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.Promotor", "Promotor")
                        .WithMany("Programas")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");

                    b.Navigation("Promotor");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoTarea", b =>
                {
                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromoPrograma", "Programa")
                        .WithMany("Tareas")
                        .HasForeignKey("ProgramaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programa");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoTareaPromotor", b =>
                {
                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromoProgramaPromotor", "ProgramaPromotor")
                        .WithMany("TareasAsignadas")
                        .HasForeignKey("ProgramaPromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromoTarea", "Tarea")
                        .WithMany("TareasPromotor")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ProgramaPromotor");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromotorWallet", b =>
                {
                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.Promotor", "Promotor")
                        .WithMany("Wallets")
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotor");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromotorWalletTransaccion", b =>
                {
                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromoEvento", "PromoEvento")
                        .WithMany()
                        .HasForeignKey("PromoEventoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WePlayRises.Crowdpromotion.Domain.Model.PromotorWallet", "Wallet")
                        .WithMany("Transacciones")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PromoEvento");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoPrograma", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Promotores");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoProgramaPromotor", b =>
                {
                    b.Navigation("TareasAsignadas");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromoTarea", b =>
                {
                    b.Navigation("TareasPromotor");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.Promotor", b =>
                {
                    b.Navigation("Programas");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("WePlayRises.Crowdpromotion.Domain.Model.PromotorWallet", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
