// Domain types - Re-export from shared
export type {
    PlantillaProyectoList,
    PlantillaProyecto,
    PlantillaProyectoNecesidad,
    PlantillaResumen,
    RolProfesional,
    RolProfesionalConCategoria,
    CategoriaRol,
    GenerarNecesidadesResult,
    GenerarNecesidadesRequest,
    NecesidadSeleccionada,
    PrioridadNecesidad,
    // Explorar Propuestas (US-CS-03)
    NecesidadPublicaList,
    NecesidadPublica,
    ArtistaPublico,
    MiPropuestaList,
    CreatePropuestaRequest,
    PropuestaCreatedResult,
    RetirarPropuestaResult,
    NecesidadesPublicasFilter,
    EstadoPropuesta,
    OrderByNecesidades,
    // Acuerdos, Milestones y Entregables (US-CS-04)
    Acuerdo,
    AcuerdoArtista,
    AcuerdoProfesional,
    AcuerdoNecesidad,
    AcuerdoTimelineEvento,
    Milestone,
    Entregable,
    AceptarPropuestaRequest,
    AceptarPropuestaResult,
    RechazarPropuestaRequest,
    RechazarPropuestaResult,
    CreateMilestoneRequest,
    MilestoneCreatedResult,
    CreateEntregableRequest,
    EntregableCreatedResult,
    AprobarEntregableRequest,
    AprobarEntregableResult,
    RechazarEntregableRequest,
    RechazarEntregableResult,
    CancelarAcuerdoRequest,
    CancelarAcuerdoResult,
    CompletarAcuerdoResult,
    EstadoAcuerdo,
    EstadoEntregable,
    RolAcuerdo,
    // Mensajeria (US-CS-05)
    ContextoConversacion,
    FiltroConversacion,
    CreateConversacionRequest,
    CreateConversacionResult,
    CreateMensajeRequest,
    ConversacionListItem,
    ConversacionListResponse,
    Mensaje,
    MensajeListResponse,
    MarcarLeidosResponse,
    NoLeidosCountResponse,
    // Valoraciones Bidireccionales (US-CS-06)
    CreateValoracionRequest,
    ValoracionCreatedResult,
    ValoracionResumen,
    ValoracionListItem,
    PaginatedResult,
    ValoracionesUsuario,
} from "@shared/types/crowdsourcing"
