<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WePlayRises.Core.Application\WePlayRises.Core.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EntityFramework\EntityFramework.csproj" />
  </ItemGroup>

</Project>
