<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WePlayRises.Crowdsourcing.Application\WePlayRises.Crowdsourcing.Application.csproj" />
    <ProjectReference Include="..\WePlayRises.Crowdsourcing.Domain\WePlayRises.Crowdsourcing.Domain.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\EntityFramework\EntityFramework.csproj" />
  </ItemGroup>

</Project>
