<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Kernel\Kernel.csproj" />
    <ProjectReference Include="..\WePlayRises.Crowdfunding.Application\WePlayRises.Crowdfunding.Application.csproj" />
    <ProjectReference Include="..\WePlayRises.Crowdfunding.Infra\WePlayRises.Crowdfunding.Infra.csproj" />
  </ItemGroup>

</Project>
