import type {
    DashboardResumen,
    MiCampaniaListItem,
    CampaniaBackingList,
    CampaniaStatsDetail,
} from "@shared/types"

export const mockDashboardResumen: DashboardResumen = {
    artistaId: "artista-123",
    nombreArtistico: "Usuario 1 Music Actualizado",
    totalRecaudado: 15340.5,
    totalBackers: 487,
    campaniasActivas: 2,
    campaniasCompletadas: 3,
    totalCampanias: 5,
    monedaSimbolo: "EUR",
    fechaUltimoAporte: "2026-02-14T10:30:00Z",
}

export const mockDashboardResumenEmpty: DashboardResumen = {
    artistaId: "artista-123",
    nombreArtistico: "Usuario 1 Music Actualizado",
    totalRecaudado: 0,
    totalBackers: 0,
    campaniasActivas: 0,
    campaniasCompletadas: 0,
    totalCampanias: 0,
    monedaSimbolo: "EUR",
    fechaUltimoAporte: undefined,
}

export const mockMisCampanias: MiCampaniaListItem[] = [
    {
        id: "campania-1",
        titulo: "Mi Album Debut",
        imagenPrincipalUrl: "https://example.com/album.jpg",
        estadoCampaniaId: 2,
        estadoCampaniaNombre: "Publicada",
        importeObjetivo: 5000.0,
        importeRecaudado: 2340.5,
        porcentajeProgreso: 46.81,
        numBackers: 78,
        diasRestantes: 46,
        fechaFin: "2026-03-31T23:59:59Z",
        fechaCreacion: "2026-01-15T12:00:00Z",
    },
    {
        id: "campania-2",
        titulo: "Gira Nacional 2026",
        imagenPrincipalUrl: "https://example.com/gira.jpg",
        estadoCampaniaId: 2,
        estadoCampaniaNombre: "Publicada",
        importeObjetivo: 10000.0,
        importeRecaudado: 7890.0,
        porcentajeProgreso: 78.9,
        numBackers: 234,
        diasRestantes: 15,
        fechaFin: "2026-03-01T23:59:59Z",
        fechaCreacion: "2026-01-10T09:00:00Z",
    },
    {
        id: "campania-3",
        titulo: "EP Acustico",
        imagenPrincipalUrl: undefined,
        estadoCampaniaId: 1,
        estadoCampaniaNombre: "Borrador",
        importeObjetivo: 3000.0,
        importeRecaudado: 0.0,
        porcentajeProgreso: 0.0,
        numBackers: 0,
        diasRestantes: undefined,
        fechaFin: undefined,
        fechaCreacion: "2026-02-10T09:00:00Z",
    },
]

export const mockCampaniaBackings: CampaniaBackingList = {
    campaniaId: "campania-1",
    campaniaTitulo: "Mi Album Debut",
    stats: {
        totalRecaudado: 2340.5,
        backingPromedio: 30.01,
        totalBackers: 78,
        rewardMasPopular: "CD Fisico Firmado",
        ultimoBacking: {
            nombreBacker: "Maria Lopez",
            monto: 25.0,
            fechaCreacion: "2026-02-14T10:30:00Z",
        },
    },
    backings: {
        items: [
            {
                id: "backing-1",
                nombreBacker: "Maria Lopez",
                email: "maria.lopez@example.com",
                monto: 25.0,
                rewardNombre: "CD Fisico Firmado",
                mensaje: "Mucha suerte con el proyecto!",
                esAnonimo: false,
                estadoPedido: "Completado",
                fechaCreacion: "2026-02-14T10:30:00Z",
            },
            {
                id: "backing-2",
                nombreBacker: "Anonimo",
                email: undefined,
                monto: 50.0,
                rewardNombre: undefined,
                mensaje: undefined,
                esAnonimo: true,
                estadoPedido: "Completado",
                fechaCreacion: "2026-02-13T09:15:00Z",
            },
            {
                id: "backing-3",
                nombreBacker: "Carlos Sanchez",
                email: "carlos@example.com",
                monto: 100.0,
                rewardNombre: "Vinilo Limitado",
                mensaje: undefined,
                esAnonimo: false,
                estadoPedido: "Completado",
                fechaCreacion: "2026-02-12T15:45:00Z",
            },
        ],
        totalCount: 78,
        page: 1,
        pageSize: 20,
        totalPages: 4,
    },
}

export const mockCampaniaStats: CampaniaStatsDetail = {
    campaniaId: "campania-1",
    campaniaTitulo: "Mi Album Debut",
    importeObjetivo: 5000.0,
    importeRecaudado: 2340.5,
    porcentajeProgreso: 46.81,
    numBackers: 78,
    backingPromedio: 30.01,
    diasRestantes: 46,
    diasTranscurridos: 14,
    totalDiasCampania: 60,
    proyeccionFinal: 10029.64,
    velocidadDiaria: 167.18,
    rewardStats: [
        {
            rewardId: "reward-1",
            rewardNombre: "Descarga Digital",
            cantidadVendida: 45,
            totalRecaudado: 450.0,
            porcentajeDelTotal: 19.23,
        },
        {
            rewardId: "reward-2",
            rewardNombre: "CD Fisico Firmado",
            cantidadVendida: 33,
            totalRecaudado: 825.0,
            porcentajeDelTotal: 35.25,
        },
    ],
    progressoPorDia: [
        {
            fecha: "2026-02-01",
            numBackings: 12,
            totalRecaudado: 340.0,
            acumulado: 340.0,
        },
        {
            fecha: "2026-02-02",
            numBackings: 8,
            totalRecaudado: 210.0,
            acumulado: 550.0,
        },
    ],
}
