// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WePlayRises.Crowdfunding.Infra.Context;

#nullable disable

namespace WePlayRises.Crowdfunding.Infra.Migrations
{
    [DbContext(typeof(CrowdfundingContext))]
    partial class CrowdfundingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.AportacionCrowdfunding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoOperacionPasarela")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoOperacionProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoAportacionId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoAportacion_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteComisionPasarela")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteComisionPlataforma")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteImpuestos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteNetoArtista")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("MetodoPago_Id");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<Guid>("PedidoCrowdfundingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PedidoCrowdfunding_Id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoCrowdfundingId", "EstadoAportacionId")
                        .HasDatabaseName("IX_AportacionCrowdfunding_Pedido_Estado");

                    b.ToTable("AportacionCrowdfunding", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CodigoOperacionPasarela")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CodigoOperacionProveedor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EstadoAportacionId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoAportacion_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaAutorizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaCaptura")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteComisionPasarela")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteComisionPlataforma")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteImpuestos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteNetoArtista")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("MembershipSuscripcionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MembershipSuscripcion_Id");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int")
                        .HasColumnName("MetodoPago_Id");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.HasKey("Id");

                    b.HasIndex("MembershipSuscripcionId", "EstadoAportacionId")
                        .HasDatabaseName("IX_Artista_MembershipPago_Suscripcion");

                    b.ToTable("Artista_MembershipPago", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteMensual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("NombrePlan")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId", "NombrePlan")
                        .IsUnique()
                        .HasDatabaseName("IX_Artista_MembershipPlan_Artista_NombrePlan");

                    b.ToTable("Artista_MembershipPlan", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipSuscripcion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<bool>("EsActiva")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaFin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaInicio")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("MembershipPlanId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MembershipPlan_Id");

                    b.Property<DateTime?>("ProximoCargo")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MembershipPlanId");

                    b.HasIndex("ArtistaId", "UserId", "EsActiva")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("IX_Artista_MembershipSuscripcion_Artista_User");

                    b.ToTable("Artista_MembershipSuscripcion", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaPayoutCuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<bool>("EsPorDefecto")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaBaja")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Iban")
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)")
                        .HasColumnName("IBAN");

                    b.Property<string>("IdentificadorExterno")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NombreTitular")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProveedorPayout")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId", "EsPorDefecto")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Artista_PayoutCuenta_Artista_Id");

                    b.ToTable("Artista_PayoutCuenta", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Artista_Id");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<string>("DescripcionCorta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EstadoCampaniaId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoCampania_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaFin")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaInicio")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("ImagenPrincipalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("ImporteMinimo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteObjetivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImportePledgedActual")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<bool>("PermiteAportacionesAnonimas")
                        .HasColumnType("bit");

                    b.Property<bool>("PermitePropinas")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PorcentajeComisionPlataforma")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<Guid?>("ProyectoArtisticoId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ProyectoArtistico_Id");

                    b.Property<string>("Subtitulo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TipoFinanciacionId")
                        .HasColumnType("int")
                        .HasColumnName("TipoFinanciacion_Id");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("VideoPrincipalUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaId", "EstadoCampaniaId")
                        .HasDatabaseName("IX_CampaniaCrowdfunding_Artista_Estado");

                    b.ToTable("CampaniaCrowdfunding", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingComentario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Borrado")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Campania_Id");

                    b.Property<Guid?>("ComentarioPadreId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ComentarioPadre_Id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsRespuestaArtista")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.HasIndex("ComentarioPadreId");

                    b.ToTable("CampaniaCrowdfunding_Comentario", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingPayout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArtistaPayoutCuentaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ArtistaPayoutCuenta_Id");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Campania_Id");

                    b.Property<int>("EstadoPayoutId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoPayout_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("FechaProgramada")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteBruto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteComisionPasarela")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteComisionPlataforma")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteImpuestosRetenidos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteNetoArtista")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<string>("NotasInternas")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ArtistaPayoutCuentaId");

                    b.HasIndex("CampaniaId", "EstadoPayoutId")
                        .HasDatabaseName("IX_CampaniaCrowdfunding_Payout_Campania_Estado");

                    b.ToTable("CampaniaCrowdfunding_Payout", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingReward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Campania_Id");

                    b.Property<int?>("CantidadMaxima")
                        .HasColumnType("int");

                    b.Property<int?>("CantidadPorBacker")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasColumnType("bit");

                    b.Property<bool>("EsAddOn")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteMinimo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IncluyeEnvioFisico")
                        .HasColumnType("bit");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("TiempoEntregaEstimado")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TipoRewardId")
                        .HasColumnType("int")
                        .HasColumnName("TipoReward_Id");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId", "Orden")
                        .HasDatabaseName("IX_CampaniaCrowdfunding_Reward_Campania_Orden");

                    b.ToTable("CampaniaCrowdfunding_Reward", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingStretchGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Alcanzado")
                        .HasColumnType("bit");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Campania_Id");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaAlcanzado")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteObjetivo")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.ToTable("CampaniaCrowdfunding_StretchGoal", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingUpdate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Campania_Id");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsPublico")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("SoloBackers")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId");

                    b.ToTable("CampaniaCrowdfunding_Update", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfunding", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaniaId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Campania_Id");

                    b.Property<string>("ComentarioBacker")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("DireccionEnvioId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DireccionEnvio_Id");

                    b.Property<int>("EstadoPedidoId")
                        .HasColumnType("int")
                        .HasColumnName("EstadoPedido_Id");

                    b.Property<Guid?>("FanProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("FanProfile_Id");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteEnvio")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteImpuestos")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImportePropina")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteSubtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int")
                        .HasColumnName("Moneda_Id");

                    b.Property<bool>("PermitirMostrarNombre")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CampaniaId", "EstadoPedidoId")
                        .HasDatabaseName("IX_PedidoCrowdfunding_Campania_Estado");

                    b.ToTable("PedidoCrowdfunding", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfundingLinea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<bool>("EsRewardPrincipal")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasPrecision(3)
                        .HasColumnType("datetime2(3)");

                    b.Property<decimal>("ImporteLinea")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("PedidoCrowdfundingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PedidoCrowdfunding_Id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<Guid>("RewardId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Reward_Id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoCrowdfundingId")
                        .HasDatabaseName("IX_PedidoCrowdfunding_Linea_Pedido");

                    b.HasIndex("RewardId");

                    b.ToTable("PedidoCrowdfunding_Linea", (string)null);
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.AportacionCrowdfunding", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfunding", "PedidoCrowdfunding")
                        .WithMany("Aportaciones")
                        .HasForeignKey("PedidoCrowdfundingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoCrowdfunding");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipPago", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipSuscripcion", "MembershipSuscripcion")
                        .WithMany("Pagos")
                        .HasForeignKey("MembershipSuscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MembershipSuscripcion");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipSuscripcion", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipPlan", "MembershipPlan")
                        .WithMany("Suscripciones")
                        .HasForeignKey("MembershipPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MembershipPlan");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingComentario", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", "Campania")
                        .WithMany("Comentarios")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingComentario", "ComentarioPadre")
                        .WithMany("Respuestas")
                        .HasForeignKey("ComentarioPadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Campania");

                    b.Navigation("ComentarioPadre");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingPayout", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.ArtistaPayoutCuenta", "ArtistaPayoutCuenta")
                        .WithMany("Payouts")
                        .HasForeignKey("ArtistaPayoutCuentaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", "Campania")
                        .WithMany("Payouts")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtistaPayoutCuenta");

                    b.Navigation("Campania");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingReward", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", "Campania")
                        .WithMany("Rewards")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campania");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingStretchGoal", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", "Campania")
                        .WithMany("StretchGoals")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campania");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingUpdate", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", "Campania")
                        .WithMany("Updates")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campania");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfunding", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", "Campania")
                        .WithMany("Pedidos")
                        .HasForeignKey("CampaniaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Campania");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfundingLinea", b =>
                {
                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfunding", "PedidoCrowdfunding")
                        .WithMany("Lineas")
                        .HasForeignKey("PedidoCrowdfundingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingReward", "Reward")
                        .WithMany("Lineas")
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PedidoCrowdfunding");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipPlan", b =>
                {
                    b.Navigation("Suscripciones");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaMembershipSuscripcion", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.ArtistaPayoutCuenta", b =>
                {
                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfunding", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Payouts");

                    b.Navigation("Pedidos");

                    b.Navigation("Rewards");

                    b.Navigation("StretchGoals");

                    b.Navigation("Updates");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingComentario", b =>
                {
                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.CampaniaCrowdfundingReward", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("WePlayRises.Crowdfunding.Domain.Model.PedidoCrowdfunding", b =>
                {
                    b.Navigation("Aportaciones");

                    b.Navigation("Lineas");
                });
#pragma warning restore 612, 618
        }
    }
}
