<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WePlayRises.BuildingBlocks.$(MSBuildProjectName)</AssemblyName>
    <RootNamespace>WePlayRises.BuildingBlocks.$(MSBuildProjectName)</RootNamespace>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <FileVersion>1.0.0</FileVersion>
    <Description>WePlayRises.BuildingBlocks.Kernel contains core infrastructure for CQRS, ServiceResponse, and validation.</Description>
    <Copyright>Copyright © 2026</Copyright>
    <Authors>WePlayRises</Authors>
    <Company>WePlayRises</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
  </ItemGroup>

</Project>
